#!/usr/bin/env python3
"""Build the Auth0 API tube-style map.

Generated by batch generator. 
"""

import sys
from pathlib import Path

sys.path.insert(0, "/Users/kinlane/GitHub/all/.claude/skills")
from _subway_engine import build_subway  # noqa: E402

ABBREV = {

}

LINES = [
    {
        "name": 'Auth0 Platform',
        "color": '#EB5424',
        "closed": True,
        "stations": [
        ('Management', (640, 260)),
        ('Authentication', (840, 460)),
        ('My Account', (640, 660)),
        ('My Organization', (440, 460)),
        ],
    },
]

URL_OVERRIDES = {
    'Management': 'https://apis.apis.io/apis/auth0/auth0-management-api/',
    'Authentication': 'https://apis.apis.io/apis/auth0/auth0-authentication-api/',
    'My Account': 'https://apis.apis.io/apis/auth0/auth0-my-account-api/',
    'My Organization': 'https://apis.apis.io/apis/auth0/auth0-my-organization-api/',
}


def main():
    seen = set()
    n_unique = 0
    for ln in LINES:
        for (st, _) in ln["stations"]:
            if st not in seen:
                n_unique += 1
                seen.add(st)
    build_subway(
        title='The Auth0 API · Underground Map',
        subtitle=f"{n_unique} APIs · {len(LINES)} functional lines · click any station for the apis.io page",
        lines=LINES,
        abbrev=ABBREV,
        source_label='Source: auth0/openapi · github.com/api-evangelist/auth0',
        out_dir=Path(__file__).resolve().parent,
        out_basename='auth0-subway-map',
        provider_id='auth0',
        station_url_overrides=URL_OVERRIDES,
    )


if __name__ == "__main__":
    main()
