openapi: 3.0.0
info:
  title: Auth0 Authentication actions anomaly API
  description: Auth0 Authentication API. Endpoints for authentication and authorization using OpenID Connect, OAuth 2.0, SAML, WS-Federation, and Passwordless flows.
  version: 1.0.0
servers:
- url: '{auth0_domain}'
  description: The Authentication API is served over HTTPS.
  variables:
    auth0_domain:
      description: Auth0 domain
      default: https://demo.us.auth0.com
tags:
- name: anomaly
paths:
  /anomaly/blocks/ips/{id}:
    get:
      summary: Check If an IP Address Is Blocked
      description: Check if the given IP address is blocked via the <a href="https://auth0.com/docs/configure/attack-protection/suspicious-ip-throttling">Suspicious IP Throttling</a> due to multiple suspicious attempts.
      tags:
      - anomaly
      parameters:
      - name: id
        in: path
        description: IP address to check.
        required: true
        schema:
          $ref: '#/components/schemas/AnomalyIPFormat'
      responses:
        '200':
          description: IP address specified is currently blocked.
        '400':
          description: Connection does not exist.
          x-description-1: Invalid request URI. The message will vary depending on the cause.
        '401':
          description: Invalid token.
          x-description-1: Client is not global.
          x-description-2: Invalid signature received for JSON Web Token validation.
        '403':
          description: 'Insufficient scope; expected any of: get:anomaly_block.'
        '404':
          description: IP address specified is not currently blocked.
        '429':
          description: Too many requests. Check the X-RateLimit-Limit, X-RateLimit-Remaining and X-RateLimit-Reset headers.
      operationId: get_ips_by_id
      x-release-lifecycle: GA
      x-operation-name: checkIp
      x-operation-group:
      - anomaly
      - blocks
      security:
      - bearerAuth: []
      - oAuth2ClientCredentials:
        - read:anomaly_blocks
    delete:
      summary: Remove the Blocked IP Address
      description: Remove a block imposed by <a href="https://auth0.com/docs/configure/attack-protection/suspicious-ip-throttling">Suspicious IP Throttling</a> for the given IP address.
      tags:
      - anomaly
      parameters:
      - name: id
        in: path
        description: IP address to unblock.
        required: true
        schema:
          $ref: '#/components/schemas/AnomalyIPFormat'
      responses:
        '204':
          description: IP address specified successfully unblocked.
        '400':
          description: Connection does not exist.
          x-description-1: Invalid request URI. The message will vary depending on the cause.
        '401':
          description: Invalid token.
          x-description-1: Client is not global.
          x-description-2: Invalid signature received for JSON Web Token validation.
        '403':
          description: 'Insufficient scope; expected any of: delete:anomaly_block.'
        '429':
          description: Too many requests. Check the X-RateLimit-Limit, X-RateLimit-Remaining and X-RateLimit-Reset headers.
      operationId: delete_ips_by_id
      x-release-lifecycle: GA
      x-operation-name: unblockIp
      x-operation-group:
      - anomaly
      - blocks
      security:
      - bearerAuth: []
      - oAuth2ClientCredentials:
        - delete:anomaly_blocks
components:
  schemas:
    AnomalyIPFormat:
      type: string
      oneOf:
      - type: string
        format: ipv4
      - type: string
        format: ipv6
      description: IP address to check.
