naftiko: 1.0.0-alpha2
info:
  label: "Auth0 Management API \u2014 Connections Scim Configurations"
  description: Auth0 Management API capability covering the Connections Scim Configurations resource group (1 paths). Self-contained Naftiko capability
    covering one Auth0 Management surface. 1 operations.
  tags:
  - Auth0
  - Management API
  - Connections Scim Configurations
  created: '2026-05-22'
  modified: '2026-05-22'
binds:
- namespace: env
  keys:
    AUTH0_DOMAIN: AUTH0_DOMAIN
    AUTH0_MGMT_TOKEN: AUTH0_MGMT_TOKEN
capability:
  consumes:
  - type: http
    namespace: auth0-management-connections-scim-configurations
    baseUri: https://{AUTH0_DOMAIN}/api/v2
    description: "Auth0 Management API \u2014 Connections Scim Configurations resource group. Self-contained."
    resources:
    - name: connections-scim-configurations
      path: /connections-scim-configurations
      operations:
      - name: get_connections-scim-configurations
        method: GET
        description: Get a List of SCIM Configurations
        outputRawFormat: json
