naftiko: 1.0.0-alpha2
info:
  label: "Auth0 Management API \u2014 Rules Configs"
  description: Auth0 Management API capability covering the Rules Configs resource group (2 paths). Self-contained Naftiko capability covering
    one Auth0 Management surface. 3 operations.
  tags:
  - Auth0
  - Management API
  - Rules Configs
  created: '2026-05-22'
  modified: '2026-05-22'
binds:
- namespace: env
  keys:
    AUTH0_DOMAIN: AUTH0_DOMAIN
    AUTH0_MGMT_TOKEN: AUTH0_MGMT_TOKEN
capability:
  consumes:
  - type: http
    namespace: auth0-management-rules-configs
    baseUri: https://{AUTH0_DOMAIN}/api/v2
    description: "Auth0 Management API \u2014 Rules Configs resource group. Self-contained."
    resources:
    - name: rules-configs
      path: /rules-configs
      operations:
      - name: get_rules-configs
        method: GET
        description: Retrieve Config Variable Keys for Rules (get_rules-configs)
        outputRawFormat: json
    - name: rules-configs-key
      path: /rules-configs/{key}
      operations:
      - name: delete_rules-configs_by_key
        method: DELETE
        description: Delete Rules Config for a Given Key
        outputRawFormat: json
      - name: put_rules-configs_by_key
        method: PUT
        description: Set Rules Config for a Given Key
        outputRawFormat: json
